#!/bin/bash

# Flash application
mos flash

# Change device ID
MAC=$(mos call sys.getinfo | grep "mac" | sed -E 's/\s*"mac": "(.*)",\s*/\1/')
mos config-set device.id=$MAC
mos call sys.reboot

# Populate web server
for file in web/*; do
    data=""
    if [[ $file == "web/index.html" ]]; then
        data=$(cat $file | sed -E "s/\{\{ DEVICE_ID \}\}/$MAC/")
    else
        data=$(cat $file)
    fi
    data=$(echo $data | base64 -w 0)
    mos call fs.put "{\"filename\": \"/$file\", \"data\": \"$data\"}"
done

# Provision with AWS IoT
mos aws-iot-setup --aws-region us-east-1 --aws-iot-policy default

# Open console
mos console
