#!/bin/bash

[[ -z $1 ]] && exit 1
grep "\[$1\]" devices/config &>/dev/null
[[ $? -ne 0 ]] && exit 1

device=$1
endpoint=$(grep -A 2 "\[$1\]" devices/config | grep endpoint | sed -E 's/\s*endpoint = (.*)\s*/\1/')

port="--port mqtts://$endpoint/$device"
cert="--cert-file devices/aws-$device.crt.pem"
key="--key-file devices/aws-$device.key.pem"

if [ "$2" == "--update" ]; then
    dir="fs/*.js"
    if [[ -n $3 ]] && [[ -d "examples/$3" ]]; then
        dir="examples/$3/*.js"
    fi
    for file in $dir; do
        mos $port $cert $key put $file
    done
    mos $port $cert $key call sys.reboot &>/dev/null
else
    shift
    mos $port $cert $key $@
fi
